from django.conf.urls import url, include
from django.urls import path
from . import views
from django.contrib.auth.views import *

urlpatterns = [

    url(r'^login_user/$', LoginView.as_view(template_name='home/login.html'), name='login_user'),
    url(r'^logout_user/$', LogoutView.as_view(), name='logout_user'),

    url(r'^view_profile/$', views.view_profile, name='view_profile'),
    url(r'^view_profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),

    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name='home/reset_password.html'),
        {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done',
         'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='home/reset_password_done.html'),
        {'template_name': 'accounts/reset_password_done.html'},
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        {'template_name': 'accounts/reset_password_confirm.html',
         'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='home/login.html'),
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^index/$', views.index, name='index'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^theme/$', views.theme, name='theme'),
    url(r'^language/$', views.language, name='language'),

    url(r'^schools/$', views.school_list, name='school_list'),
    url(r'^school/create/$', views.school_create, name='school_create'),
    url(r'^school/(?P<school_id>\d+)/update/$', views.school_update, name='school_update'),
    url(r'^school/(?P<school_id>\d+)/view/$', views.school_view, name='school_view'),
    url(r'^school/(?P<school_id>\d+)/delete/$', views.school_delete, name='school_delete'),
    #
    url(r'^superusers/$', views.superuser_list, name='superuser_list'),
    url(r'^superuser/create/$', views.superuser_create, name='superuser_create'),
    url(r'^superuser/(?P<pk>\d+)/update/$', views.superuser_update, name='superuser_update'),
    url(r'^superuser/(?P<pk>\d+)/view/$', views.superuser_view, name='superuser_view'),
    url(r'^superuser/(?P<pk>\d+)/delete/$', views.superuser_delete, name='superuser_delete'),

    url(r'^(?P<school_id>\d+)/admins/$', views.admin_list, name='admin_list'),
    url(r'^(?P<school_id>\d+)/admin/create/$', views.admin_create, name='admin_create'),
    url(r'^(?P<school_id>\d+)/admin/(?P<pk>\d+)/update/$', views.admin_update, name='admin_update'),
    url(r'^(?P<school_id>\d+)/admin/(?P<pk>\d+)/view/$', views.admin_view, name='admin_view'),
    url(r'^(?P<school_id>\d+)/admin/(?P<pk>\d+)/delete/$', views.admin_delete, name='admin_delete'),

    url(r'^(?P<school_id>\d+)/teachers/$', views.teacher_list, name='teacher_list'),
    url(r'^(?P<school_id>\d+)/teacher/create/$', views.teacher_create, name='teacher_create'),
    url(r'^(?P<school_id>\d+)/teacher/(?P<teacher_id>\d+)/update/$', views.teacher_update, name='teacher_update'),
    url(r'^(?P<school_id>\d+)/teacher/(?P<teacher_id>\d+)/view/$', views.teacher_view, name='teacher_view'),
    url(r'^(?P<school_id>\d+)/teacher/(?P<teacher_id>\d+)/delete/$', views.teacher_delete, name='teacher_delete'),

    url(r'^(?P<school_id>\d+)/designations/$', views.designation_list, name='designation_list'),
    url(r'^(?P<school_id>\d+)/designation/create/$', views.designation_create, name='designation_create'),
    url(r'^(?P<school_id>\d+)/designation/(?P<designation_id>\d+)/update/$', views.designation_update,
        name='designation_update'),
    url(r'^(?P<school_id>\d+)/designation/(?P<designation_id>\d+)/view/$', views.designation_view,
        name='designation_view'),
    url(r'^(?P<school_id>\d+)/designation/(?P<designation_id>\d+)/delete/$', views.designation_delete,
        name='designation_delete'),

    url(r'^(?P<school_id>\d+)/employees/$', views.employee_list, name='employee_list'),
    url(r'^(?P<school_id>\d+)/employee/create/$', views.employee_create, name='employee_create'),
    url(r'^(?P<school_id>\d+)/employee/(?P<employee_id>\d+)/update/$', views.employee_update, name='employee_update'),
    url(r'^(?P<school_id>\d+)/employee/(?P<employee_id>\d+)/view/$', views.employee_view, name='employee_view'),
    url(r'^(?P<school_id>\d+)/employee/(?P<employee_id>\d+)/delete/$', views.employee_delete, name='employee_delete'),

    url(r'^(?P<school_id>\d+)/students/$', views.student_list, name='student_list'),
    url(r'^(?P<school_id>\d+)/student/create/$', views.student_create, name='student_create'),
    url(r'^(?P<school_id>\d+)/student/(?P<student_id>\d+)/update/$', views.student_update, name='student_update'),
    url(r'^(?P<school_id>\d+)/student/(?P<student_id>\d+)/view/$', views.student_view, name='student_view'),
    url(r'^(?P<school_id>\d+)/student/(?P<student_id>\d+)/delete/$', views.student_delete, name='student_delete'),

    url(r'^(?P<school_id>\d+)/guardians/$', views.guardian_list, name='guardian_list'),
    url(r'^(?P<school_id>\d+)/guardian/create/$', views.guardian_create, name='guardian_create'),
    url(r'^(?P<school_id>\d+)/guardian/(?P<guardian_id>\d+)/update/$', views.guardian_update, name='guardian_update'),
    url(r'^(?P<school_id>\d+)/guardian/(?P<guardian_id>\d+)/view/$', views.guardian_view, name='guardian_view'),
    url(r'^(?P<school_id>\d+)/guardian/(?P<guardian_id>\d+)/delete/$', views.guardian_delete, name='guardian_delete'),

    url(r'^(?P<school_id>\d+)/classrooms/$', views.classroom_list, name='classroom_list'),
    url(r'^(?P<school_id>\d+)/classroom/create/$', views.classroom_create, name='classroom_create'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/update/$', views.classroom_update,
        name='classroom_update'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/view/$', views.classroom_view, name='classroom_view'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/delete/$', views.classroom_delete,
        name='classroom_delete'),

    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/sections/$', views.section_list, name='section_list'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/section/create/$', views.section_create,
        name='section_create'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/section/(?P<section_id>\d+)/update/$',
        views.section_update, name='section_update'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/section/(?P<section_id>\d+)/view/$', views.section_view,
        name='section_view'),
    url(r'^(?P<school_id>\d+)/classroom/(?P<classroom_id>\d+)/section/(?P<section_id>\d+)/delete/$',
        views.section_delete, name='section_delete'),

    url(r'^(?P<school_id>\d+)/years/$', views.year_list, name='year_list'),
    url(r'^(?P<school_id>\d+)/year/create/$', views.year_create, name='year_create'),
    url(r'^(?P<school_id>\d+)/year/(?P<year_id>\d+)/view/$', views.year_view, name='year_view'),
    url(r'^(?P<school_id>\d+)/year/(?P<year_id>\d+)/update/$', views.year_update, name='year_update'),
    url(r'^(?P<school_id>\d+)/year/(?P<year_id>\d+)/delete/$', views.year_delete, name='year_delete'),

    url(r'^(?P<school_id>\d+)/syllabus/$', views.syllabus_list, name='syllabus_list'),
    url(r'^(?P<school_id>\d+)/syllabus/create/$', views.syllabus_create, name='syllabus_create'),
    url(r'^(?P<school_id>\d+)/syllabus/(?P<syllabus_id>\d+)/update/$', views.syllabus_update, name='syllabus_update'),
    url(r'^(?P<school_id>\d+)/syllabus/(?P<syllabus_id>\d+)/delete/$', views.syllabus_delete, name='syllabus_delete'),

    url(r'^(?P<school_id>\d+)/subjects/$', views.subject_list, name='subject_list'),
    url(r'^(?P<school_id>\d+)/subject/create/$', views.subject_create, name='subject_create'),
    url(r'^(?P<school_id>\d+)/subject/(?P<subject_id>\d+)/update/$', views.subject_update, name='subject_update'),
    url(r'^(?P<school_id>\d+)/subject/(?P<subject_id>\d+)/delete/$', views.subject_delete, name='subject_delete'),

    url(r'^(?P<school_id>\d+)/routines/$', views.routine_list, name='routine_list'),
    url(r'^(?P<school_id>\d+)/routine/create/$', views.routine_create, name='routine_create'),
    url(r'^(?P<school_id>\d+)/routine/(?P<routine_id>\d+)/update/$', views.routine_update, name='routine_update'),
    url(r'^(?P<school_id>\d+)/routine/(?P<routine_id>\d+)/delete/$', views.routine_delete, name='routine_delete'),

    url(r'^(?P<school_id>\d+)/bulk_students/$', views.bulk_student_list, name='bulk_student_list'),
    url(r'^(?P<school_id>\d+)/bulk_student/create/$', views.bulk_student_create, name='bulk_student_create'),

    url(r'^(?P<school_id>\d+)/assignments/$', views.assignment_list, name='assignment_list'),
    url(r'^(?P<school_id>\d+)/assignment/create/$', views.assignment_create, name='assignment_create'),
    url(r'^(?P<school_id>\d+)/assignment/(?P<assignment_id>\d+)/update/$', views.assignment_update,
        name='assignment_update'),
    url(r'^(?P<school_id>\d+)/assignment/(?P<assignment_id>\d+)/delete/$', views.assignment_delete,
        name='assignment_delete'),

    url(r'^(?P<school_id>\d+)/exam_grades/$', views.exam_grade_list, name='exam_grade_list'),
    url(r'^(?P<school_id>\d+)/exam_grade/create/$', views.exam_grade_create, name='exam_grade_create'),
    url(r'^(?P<school_id>\d+)/exam_grade/(?P<exam_grade_id>\d+)/update/$', views.exam_grade_update,
        name='exam_grade_update'),
    url(r'^(?P<school_id>\d+)/exam_grade/(?P<exam_grade_id>\d+)/delete/$', views.exam_grade_delete,
        name='exam_grade_delete'),

    url(r'^(?P<school_id>\d+)/exams/$', views.exam_list, name='exam_list'),
    url(r'^(?P<school_id>\d+)/exam/create/$', views.exam_create, name='exam_create'),
    url(r'^(?P<school_id>\d+)/exam/(?P<exam_id>\d+)/update/$', views.exam_update, name='exam_update'),
    url(r'^(?P<school_id>\d+)/exam/(?P<exam_id>\d+)/delete/$', views.exam_delete, name='exam_delete'),

    url(r'^(?P<school_id>\d+)/exam_schedules/$', views.exam_schedule_list, name='exam_schedule_list'),
    url(r'^(?P<school_id>\d+)/exam_schedule/create/$', views.exam_schedule_create, name='exam_schedule_create'),
    url(r'^(?P<school_id>\d+)/exam_schedule/(?P<exam_schedule_id>\d+)/update/$', views.exam_schedule_update,
        name='exam_schedule_update'),
    url(r'^(?P<school_id>\d+)/exam_schedule/(?P<exam_schedule_id>\d+)/delete/$', views.exam_schedule_delete,
        name='exam_schedule_delete'),

    url(r'^(?P<school_id>\d+)/exam_suggestions/$', views.exam_suggestion_list, name='exam_suggestion_list'),
    url(r'^(?P<school_id>\d+)/exam_suggestion/create/$', views.exam_suggestion_create, name='exam_suggestion_create'),
    url(r'^(?P<school_id>\d+)/exam_suggestion/(?P<exam_suggestion_id>\d+)/update/$', views.exam_suggestion_update,
        name='exam_suggestion_update'),
    url(r'^(?P<school_id>\d+)/exam_suggestion/(?P<exam_suggestion_id>\d+)/delete/$', views.exam_suggestion_delete,
        name='exam_suggestion_delete'),

    url(r'^(?P<school_id>\d+)/certificates/$', views.certificate_list, name='certificate_list'),
    url(r'^(?P<school_id>\d+)/certificate/create/$', views.certificate_create, name='certificate_create'),
    url(r'^(?P<school_id>\d+)/certificate/(?P<certificate_id>\d+)/update/$', views.certificate_update,
        name='certificate_update'),
    url(r'^(?P<school_id>\d+)/certificate/(?P<certificate_id>\d+)/delete/$', views.certificate_delete,
        name='certificate_delete'),

    url(r'^(?P<school_id>\d+)/books/$', views.book_list, name='book_list'),
    url(r'^(?P<school_id>\d+)/book/create/$', views.book_create, name='book_create'),
    url(r'^(?P<school_id>\d+)/book/(?P<book_id>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^(?P<school_id>\d+)/book/(?P<book_id>\d+)/view/$', views.book_view, name='book_view'),
    url(r'^(?P<school_id>\d+)/book/(?P<book_id>\d+)/delete/$', views.book_delete, name='book_delete'),

    url(r'^(?P<school_id>\d+)/library_members/$', views.library_member_list, name='library_member_list'),
    url(r'^(?P<school_id>\d+)/library_member/create/$', views.library_member_create, name='library_member_create'),
    url(r'^(?P<school_id>\d+)/library_member/(?P<library_member_id>\d+)/update/$', views.library_member_update,
        name='library_member_update'),
    url(r'^(?P<school_id>\d+)/library_member/(?P<library_member_id>\d+)/delete/$', views.library_member_delete,
        name='library_member_delete'),

    url(r'^(?P<school_id>\d+)/issues/$', views.issue_list, name='issue_list'),
    url(r'^(?P<school_id>\d+)/issue/create/$', views.issue_create, name='issue_create'),
    url(r'^(?P<school_id>\d+)/issue/(?P<issue_id>\d+)/update/$', views.issue_update, name='issue_update'),
    url(r'^(?P<school_id>\d+)/issue/(?P<issue_id>\d+)/delete/$', views.issue_delete, name='issue_delete'),

    url(r'^(?P<school_id>\d+)/vehicles/$', views.vehicle_list, name='vehicle_list'),
    url(r'^(?P<school_id>\d+)/vehicle/create/$', views.vehicle_create, name='vehicle_create'),
    url(r'^(?P<school_id>\d+)/vehicle/(?P<vehicle_id>\d+)/update/$', views.vehicle_update, name='vehicle_update'),
    url(r'^(?P<school_id>\d+)/vehicle/(?P<vehicle_id>\d+)/delete/$', views.vehicle_delete, name='vehicle_delete'),

    url(r'^(?P<school_id>\d+)/routes/$', views.route_list, name='route_list'),
    url(r'^(?P<school_id>\d+)/route/create/$', views.route_create, name='route_create'),
    url(r'^(?P<school_id>\d+)/route/(?P<route_id>\d+)/update/$', views.route_update, name='route_update'),
    url(r'^(?P<school_id>\d+)/route/(?P<route_id>\d+)/delete/$', views.route_delete, name='route_delete'),

    url(r'^(?P<school_id>\d+)/transport_members/$', views.transport_member_list, name='transport_member_list'),
    url(r'^(?P<school_id>\d+)/transport_member/create/$', views.transport_member_create,
        name='transport_member_create'),
    url(r'^(?P<school_id>\d+)/transport_member/(?P<transport_member_id>\d+)/update/$', views.transport_member_update,
        name='transport_member_update'),
    url(r'^(?P<school_id>\d+)/transport_member/(?P<transport_member_id>\d+)/delete/$', views.transport_member_delete,
        name='transport_member_delete'),

    url(r'^(?P<school_id>\d+)/hostels/$', views.hostel_list, name='hostel_list'),
    url(r'^(?P<school_id>\d+)/hostel/create/$', views.hostel_create, name='hostel_create'),
    url(r'^(?P<school_id>\d+)/hostel/(?P<hostel_id>\d+)/update/$', views.hostel_update, name='hostel_update'),
    url(r'^(?P<school_id>\d+)/hostel/(?P<hostel_id>\d+)/delete/$', views.hostel_delete, name='hostel_delete'),

    url(r'^rooms/$', views.room_list, name='room_list'),
    url(r'^room/create/$', views.room_create, name='room_create'),
    url(r'^room/(?P<pk>\d+)/update/$', views.room_update, name='room_update'),
    url(r'^room/(?P<pk>\d+)/delete/$', views.room_delete, name='room_delete'),

    url(r'^(?P<school_id>\d+)/hostel_members/$', views.hostel_member_list, name='hostel_member_list'),
    url(r'^(?P<school_id>\d+)/hostel_member/create/$', views.hostel_member_create, name='hostel_member_create'),
    url(r'^(?P<school_id>\d+)/hostel_member/(?P<pk>\d+)/update/$', views.hostel_member_update, name='hostel_member_update'),
    url(r'^(?P<school_id>\d+)/hostel_member/(?P<pk>\d+)/delete/$', views.hostel_member_delete, name='hostel_member_delete'),

    url(r'^(?P<school_id>\d+)/emails/$', views.email_list, name='email_list'),
    url(r'^(?P<school_id>\d+)/email/create/$', views.email_create, name='email_create'),
    url(r'^(?P<school_id>\d+)/email/(?P<pk>\d+)/update/$', views.email_update, name='email_update'),
    url(r'^(?P<school_id>\d+)/email/(?P<pk>\d+)/delete/$', views.email_delete, name='email_delete'),

    url(r'^(?P<school_id>\d+)/smss/$', views.sms_list, name='sms_list'),
    url(r'^(?P<school_id>\d+)/sms/create/$', views.sms_create, name='sms_create'),
    url(r'^(?P<school_id>\d+)/sms/(?P<pk>\d+)/update/$', views.sms_update, name='sms_update'),
    url(r'^(?P<school_id>\d+)/sms/(?P<pk>\d+)/delete/$', views.sms_delete, name='sms_delete'),

    url(r'^(?P<school_id>\d+)/notices/$', views.notice_list, name='notice_list'),
    url(r'^(?P<school_id>\d+)/notice/create/$', views.notice_create, name='notice_create'),
    url(r'^(?P<school_id>\d+)/notice/(?P<pk>\d+)/update/$', views.notice_update, name='notice_update'),
    url(r'^(?P<school_id>\d+)/notice/(?P<pk>\d+)/delete/$', views.notice_delete, name='notice_delete'),

    url(r'^(?P<school_id>\d+)/newss/$', views.news_list, name='news_list'),
    url(r'^(?P<school_id>\d+)/news/create/$', views.news_create, name='news_create'),
    url(r'^(?P<school_id>\d+)/news/(?P<pk>\d+)/update/$', views.news_update, name='news_update'),
    url(r'^(?P<school_id>\d+)/news/(?P<pk>\d+)/delete/$', views.news_delete, name='news_delete'),

    url(r'^(?P<school_id>\d+)/holidays/$', views.holiday_list, name='holiday_list'),
    url(r'^(?P<school_id>\d+)/holiday/create/$', views.holiday_create, name='holiday_create'),
    url(r'^(?P<school_id>\d+)/holiday/(?P<pk>\d+)/update/$', views.holiday_update, name='holiday_update'),
    url(r'^(?P<school_id>\d+)/holiday/(?P<pk>\d+)/delete/$', views.holiday_delete, name='holiday_delete'),

    url(r'^(?P<school_id>\d+)/events/$', views.event_list, name='event_list'),
    url(r'^(?P<school_id>\d+)/event/create/$', views.event_create, name='event_create'),
    url(r'^(?P<school_id>\d+)/event/(?P<pk>\d+)/update/$', views.event_update, name='event_update'),
    url(r'^(?P<school_id>\d+)/event/(?P<pk>\d+)/delete/$', views.event_delete, name='event_delete'),

    url(r'^(?P<school_id>\d+)/visitors/$', views.visitor_list, name='visitor_list'),
    url(r'^(?P<school_id>\d+)/visitor/create/$', views.visitor_create, name='visitor_create'),
    url(r'^(?P<school_id>\d+)/visitor/(?P<pk>\d+)/update/$', views.visitor_update, name='visitor_update'),
    url(r'^(?P<school_id>\d+)/visitor/(?P<pk>\d+)/delete/$', views.visitor_delete, name='visitor_delete'),

    url(r'^(?P<school_id>\d+)/salary_grades/$', views.salary_grade_list, name='salary_grade_list'),
    url(r'^(?P<school_id>\d+)/salary_grade/create/$', views.salary_grade_create, name='salary_grade_create'),
    url(r'^(?P<school_id>\d+)/salary_grade/(?P<pk>\d+)/update/$', views.salary_grade_update,
        name='salary_grade_update'),
    url(r'^(?P<school_id>\d+)/salary_grade/(?P<pk>\d+)/delete/$', views.salary_grade_delete,
        name='salary_grade_delete'),

    url(r'^(?P<school_id>\d+)/discounts/$', views.discount_list, name='discount_list'),
    url(r'^(?P<school_id>\d+)/discount/create/$', views.discount_create, name='discount_create'),
    url(r'^(?P<school_id>\d+)/discount/(?P<pk>\d+)/update/$', views.discount_update, name='discount_update'),
    url(r'^(?P<school_id>\d+)/discount/(?P<pk>\d+)/delete/$', views.discount_delete, name='discount_delete'),

    url(r'^(?P<school_id>\d+)/due_fee_emails/$', views.due_fee_email_list, name='due_fee_email_list'),
    url(r'^(?P<school_id>\d+)/due_fee_email/create/$', views.due_fee_email_create, name='due_fee_email_create'),
    url(r'^(?P<school_id>\d+)/due_fee_email/(?P<pk>\d+)/update/$', views.due_fee_email_update, name='due_fee_email_update'),
    url(r'^(?P<school_id>\d+)/due_fee_email/(?P<pk>\d+)/delete/$', views.due_fee_email_delete, name='due_fee_email_delete'),

    url(r'^(?P<school_id>\d+)/due_fee_smss/$', views.due_fee_sms_list, name='due_fee_sms_list'),
    url(r'^(?P<school_id>\d+)/due_fee_sms/create/$', views.due_fee_sms_create, name='due_fee_sms_create'),
    url(r'^(?P<school_id>\d+)/due_fee_sms/(?P<pk>\d+)/update/$', views.due_fee_sms_update, name='due_fee_sms_update'),
    url(r'^(?P<school_id>\d+)/due_fee_sms/(?P<pk>\d+)/delete/$', views.due_fee_sms_delete, name='due_fee_sms_delete'),

    url(r'^(?P<school_id>\d+)/incomes/$', views.income_list, name='income_list'),
    url(r'^(?P<school_id>\d+)/income/create/$', views.income_create, name='income_create'),
    url(r'^(?P<school_id>\d+)/income/(?P<pk>\d+)/update/$', views.income_update, name='income_update'),
    url(r'^(?P<school_id>\d+)/income/(?P<pk>\d+)/delete/$', views.income_delete, name='income_delete'),

    url(r'^(?P<school_id>\d+)/income_heads/$', views.income_head_list, name='income_head_list'),
    url(r'^(?P<school_id>\d+)/income_head/create/$', views.income_head_create, name='income_head_create'),
    url(r'^(?P<school_id>\d+)/income_head/(?P<pk>\d+)/update/$', views.income_head_update, name='income_head_update'),
    url(r'^(?P<school_id>\d+)/income_head/(?P<pk>\d+)/delete/$', views.income_head_delete, name='income_head_delete'),

    url(r'^(?P<school_id>\d+)/expenditures/$', views.expenditure_list, name='expenditure_list'),
    url(r'^(?P<school_id>\d+)/expenditure/create/$', views.expenditure_create, name='expenditure_create'),
    url(r'^(?P<school_id>\d+)/expenditure/(?P<pk>\d+)/update/$', views.expenditure_update, name='expenditure_update'),
    url(r'^(?P<school_id>\d+)/expenditure/(?P<pk>\d+)/delete/$', views.expenditure_delete, name='expenditure_delete'),

    url(r'^(?P<school_id>\d+)/expenditure_heads/$', views.expenditure_head_list, name='expenditure_head_list'),
    url(r'^(?P<school_id>\d+)/expenditure_head/create/$', views.expenditure_head_create, name='expenditure_head_create'),
    url(r'^(?P<school_id>\d+)/expenditure_head/(?P<pk>\d+)/update/$', views.expenditure_head_update, name='expenditure_head_update'),
    url(r'^(?P<school_id>\d+)/expenditure_head/(?P<pk>\d+)/delete/$', views.expenditure_head_delete, name='expenditure_head_delete'),

    url(r'^(?P<school_id>\d+)/gallerys/$', views.gallery_list, name='gallery_list'),
    url(r'^(?P<school_id>\d+)/gallery/create/$', views.gallery_create, name='gallery_create'),
    url(r'^(?P<school_id>\d+)/gallery/(?P<pk>\d+)/update/$', views.gallery_update, name='gallery_update'),
    url(r'^(?P<school_id>\d+)/gallery/(?P<pk>\d+)/delete/$', views.gallery_delete, name='gallery_delete'),

    url(r'^(?P<school_id>\d+)/images/$', views.image_list, name='image_list'),
    url(r'^(?P<school_id>\d+)/image/create/$', views.image_create, name='image_create'),
    url(r'^(?P<school_id>\d+)/image/(?P<pk>\d+)/update/$', views.image_update, name='image_update'),
    url(r'^(?P<school_id>\d+)/image/(?P<pk>\d+)/delete/$', views.image_delete, name='image_delete'),

    url(r'^(?P<school_id>\d+)/sliders/$', views.slider_list, name='slider_list'),
    url(r'^(?P<school_id>\d+)/slider/create/$', views.slider_create, name='slider_create'),
    url(r'^(?P<school_id>\d+)/slider/(?P<pk>\d+)/update/$', views.slider_update, name='slider_update'),
    url(r'^(?P<school_id>\d+)/slider/(?P<pk>\d+)/delete/$', views.slider_delete, name='slider_delete'),

    url(r'^(?P<school_id>\d+)/pages/$', views.page_list, name='page_list'),
    url(r'^(?P<school_id>\d+)/page/create/$', views.page_create, name='page_create'),
    url(r'^(?P<school_id>\d+)/page/(?P<pk>\d+)/update/$', views.page_update, name='page_update'),
    url(r'^(?P<school_id>\d+)/page/(?P<pk>\d+)/delete/$', views.page_delete, name='page_delete'),

    url(r'^(?P<school_id>\d+)/teacher_attendance/$', views.teacher_attendance_list, name='teacher_attendance_list'),
    url(r'^(?P<school_id>\d+)/employee_attendance/$', views.employee_attendance_list, name='employee_attendance_list'),

    path('student_attendance/', views.student_attendance, name='student_attendance'),
    path('classrooms/ajax/', views.classrooms_ajax, name='classrooms_ajax'),
    path('classrooms/choices/ajax/', views.classrooms_choices_ajax, name='classrooms_choices_ajax'),
    path('sections/ajax/', views.sections_ajax, name='sections_ajax'),
    path('sections/choices/ajax/', views.sections_choices_ajax, name='sections_choices_ajax'),

    path('invoice/', views.invoices, name='invoices'),
    path('classrooms/ajax/', views.classroom_ajax, name='classroom_ajax'),
    path('classrooms/choices/ajax/', views.classroom_choices_ajax, name='classroom_choices_ajax'),
    path('sections/ajax/', views.section_ajax, name='section_ajax'),
    path('sections/choices/ajax/', views.section_choices_ajax, name='section_choices_ajax'),

    # path('invoices/', views.invoice_list, name='invoice_list'),
    # path('classroom/ajax/', views.classroom_ajax, name='classroom_ajax'),
    # path('classroom/choices/ajax/', views.classroom_choices_ajax, name='classroom_choices_ajax'),
    # path('section/ajax/', views.section_ajax, name='section_ajax'),
    # path('section/choices/ajax/', views.section_choices_ajax, name='section_choices_ajax'),

    # url(r'^invoices/$', views.invoice_list, name='invoice_list'),
    # url(r'^invoice/create/$', views.invoice_create, name='invoice_create'),
    # url(r'^invoice/(?P<pk>\d+)/update/$', views.invoice_update, name='invoice_update'),
    # # url(r'^invoice/(?P<pk>\d+)/view/$', views.invoice_view, name='invoice_view'),
    # url(r'^invoice/(?P<pk>\d+)/delete/$', views.invoice_delete, name='invoice_delete'),
]
