# Generated by Django 2.1.7 on 2019-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createclassinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=130)),
                ('ClassTeacher', models.CharField(blank=True, max_length=30)),
                ('TotalStudents', models.CharField(blank=True, max_length=30)),
                ('NumberOfSections', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
