# Generated by Django 2.1.7 on 2019-07-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_createclassinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Createclassinformation',
            new_name='Classinformation',
        ),
    ]
