# Generated by Django 2.1.7 on 2019-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190815_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudent',
            name='Guardian',
            field=models.CharField(default='text', max_length=130),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='GuardianRelationshipToStudent',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother', 'Mother'), ('Father', 'Father'), ('Uncle', 'Uncle'), ('Auntie', 'Auntie')], default='text', max_length=130),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='NationaId',
            field=models.CharField(default='Use NIN', max_length=150),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='PermanentAddress',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='PresentAddress',
            field=models.CharField(default='current area', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='phone',
            field=models.CharField(default='Use NIN', max_length=150),
        ),
    ]
