# Generated by Django 2.1.7 on 2019-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190815_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudent',
            name='previous_class',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='previous_school',
            field=models.CharField(default='home', max_length=100),
        ),
    ]
