# Generated by Django 2.1.7 on 2019-07-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190726_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectioninformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionName', models.CharField(max_length=130)),
                ('SectionTeacher', models.CharField(blank=True, max_length=30)),
                ('NumberOfStudents', models.CharField(blank=True, max_length=30)),
                ('NameOfClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation')),
            ],
        ),
    ]
