# Generated by Django 2.1.7 on 2019-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sectioninformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=130)),
                ('NationaId', models.CharField(max_length=130)),
                ('Responsibility', models.CharField(max_length=130)),
                ('Address', models.CharField(max_length=130)),
                ('Username', models.CharField(max_length=130)),
                ('Password', models.CharField(max_length=130)),
            ],
        ),
    ]
