# Generated by Django 2.1.7 on 2019-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190815_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudent',
            name='MotherDesignation',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='MotherName',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='MotherPhone',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='MotherProfession',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
