# Generated by Django 2.1.7 on 2019-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190815_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudent',
            name='birth_date',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='email',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='health_condition',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='datastudent',
            name='password',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
