# Generated by Django 2.1.7 on 2019-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=130)),
                ('NationaId', models.CharField(max_length=130)),
                ('Designation', models.CharField(max_length=130)),
                ('Phone', models.CharField(max_length=130)),
                ('Gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('Adress', models.CharField(max_length=130)),
                ('Religion', models.CharField(max_length=130)),
            ],
        ),
    ]
