# Generated by Django 2.1.7 on 2019-07-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_humanresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanresource',
            old_name='Adress',
            new_name='Address',
        ),
    ]
