# Generated by Django 2.1.7 on 2019-08-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190815_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastudent',
            name='reg_no',
        ),
    ]
