# Generated by Django 2.1.7 on 2019-08-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_datastudent_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Present', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='datastudent',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='datastudent',
            name='Birth_Date',
            field=models.CharField(default='nyfjhjpd', max_length=100),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='Photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.DataStudent'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='Student_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.DataStudent'),
        ),
    ]
