# Generated by Django 2.1.7 on 2019-08-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190816_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='Student_Name',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='accounts.DataStudent'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='Photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photos', to='accounts.DataStudent'),
        ),
    ]
