# Generated by Django 2.1.7 on 2019-07-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('AssignmentType', models.CharField(max_length=130)),
                ('Deadline', models.CharField(max_length=130)),
                ('Assignment', models.FileField(max_length=130, upload_to='')),
                ('Notes', models.TextField(blank=True, max_length=200)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Subjects')),
            ],
        ),
    ]
