# Generated by Django 2.1.7 on 2019-08-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190816_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='Photo',
            new_name='Photos',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='name',
            new_name='names',
        ),
    ]
