# Generated by Django 2.1.7 on 2019-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('ExamGrade', models.CharField(max_length=130)),
                ('GradePoint', models.CharField(max_length=130)),
                ('MarkFrom', models.CharField(max_length=130)),
                ('MarkTo', models.CharField(max_length=130)),
                ('Notes', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
