# Generated by Django 2.1.7 on 2019-08-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190816_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='names',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
