# Generated by Django 2.1.7 on 2019-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_examgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('ExamTitle', models.CharField(max_length=130)),
                ('StartDate', models.CharField(max_length=130)),
                ('Notes', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
