# Generated by Django 2.1.7 on 2019-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_examterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('ExamDate', models.CharField(max_length=130)),
                ('StartTime', models.CharField(max_length=130)),
                ('EndTime', models.CharField(max_length=130)),
                ('RoomNumber', models.TextField(blank=True, max_length=200)),
                ('Notes', models.TextField(blank=True, max_length=200)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation')),
                ('Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.ExamTerm')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Subjects')),
            ],
        ),
    ]
