# Generated by Django 2.1.7 on 2019-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_examschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='Notes',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='RoomNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
