# Generated by Django 2.1.7 on 2019-08-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_studentattendance_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudent',
            name='Student_Attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=130),
        ),
    ]
