# Generated by Django 2.1.7 on 2019-07-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_examsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('BookTitle', models.CharField(max_length=130)),
                ('ISBN_no', models.CharField(max_length=130)),
                ('BookId', models.CharField(max_length=130)),
                ('Edition', models.CharField(max_length=130)),
                ('Author', models.CharField(max_length=130)),
                ('Language', models.CharField(max_length=130)),
                ('Price', models.CharField(max_length=130)),
                ('Quantity', models.CharField(max_length=130)),
                ('BookCover', models.FileField(max_length=130, upload_to='')),
            ],
        ),
    ]
