# Generated by Django 2.1.7 on 2019-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_datastudent_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastudent',
            name='Student_Attendance',
            field=models.BooleanField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=130),
        ),
    ]
