# Generated by Django 2.1.7 on 2019-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('VehicleNumber', models.CharField(max_length=130)),
                ('VehicleModel', models.CharField(max_length=130)),
                ('Driver', models.CharField(max_length=130)),
                ('VehicleLicense', models.CharField(max_length=130)),
                ('VehicleContact', models.CharField(max_length=130)),
                ('Notes', models.CharField(max_length=130)),
            ],
        ),
    ]
