# Generated by Django 2.1.7 on 2019-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190816_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastudent',
            name='Student_Attendance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='none', max_length=130, null=True),
        ),
    ]
