# Generated by Django 2.1.7 on 2019-07-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('HostelName', models.CharField(max_length=130)),
                ('HostType', models.CharField(max_length=130)),
                ('Address', models.CharField(max_length=130)),
                ('Notes', models.CharField(max_length=130)),
            ],
        ),
    ]
