# Generated by Django 2.1.7 on 2019-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('Room_no', models.CharField(max_length=130)),
                ('RoomType', models.CharField(choices=[('AC', 'AC'), ('No AC ', 'No AC')], max_length=130, null=True)),
                ('SeatTotal', models.CharField(max_length=130)),
                ('CostPerSeat', models.CharField(max_length=130)),
                ('Notes', models.TextField(max_length=110)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='examsuggestion',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='HostType',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Combined', 'Combined')], max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='Notes',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='route',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='Notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='Hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Hostel'),
        ),
    ]
