# Generated by Django 2.1.7 on 2019-08-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190816_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastudent',
            name='Student_Attendance',
        ),
    ]
