# Generated by Django 2.1.7 on 2019-08-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190731_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelRoom',
            new_name='HostelRooms',
        ),
    ]
