# Generated by Django 2.1.7 on 2019-08-16 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_datastudent_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='Student_Name',
        ),
        migrations.AddField(
            model_name='datastudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 23, 12, 353913, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
