# Generated by Django 2.1.7 on 2019-08-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_vistorinfor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VistorInfor',
            new_name='VisitorInfor',
        ),
    ]
