# Generated by Django 2.1.7 on 2019-08-19 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190819_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 8, 58, 39, 928968, tzinfo=utc)),
        ),
    ]
