# Generated by Django 2.1.7 on 2019-08-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190801_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('GradeName', models.CharField(max_length=130)),
                ('BasicSalary', models.CharField(max_length=130)),
                ('HouseRent', models.CharField(max_length=130)),
                ('TransportAllowance', models.CharField(max_length=130)),
                ('MedicalAllowance', models.CharField(max_length=130)),
                ('OverTimeHourlyRate', models.CharField(max_length=130)),
                ('ProvidentFund', models.CharField(max_length=130)),
                ('HourlyRate', models.CharField(max_length=130)),
                ('TotalAllowance', models.CharField(max_length=130)),
                ('TotalDeduction', models.CharField(max_length=130)),
                ('GrossPay', models.CharField(max_length=130)),
                ('NetSalary', models.CharField(max_length=130)),
                ('Notes', models.TextField(max_length=110)),
            ],
        ),
    ]
