# Generated by Django 2.1.7 on 2019-08-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_salarygrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('Title', models.CharField(max_length=130)),
                ('Amount', models.CharField(max_length=130)),
                ('Notes', models.TextField(max_length=110)),
            ],
        ),
    ]
