# Generated by Django 2.1.7 on 2019-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('FeeTitle', models.CharField(max_length=130)),
                ('FeeType', models.CharField(choices=[('General Fee', 'General Fee'), ('Transport', 'Transport'), ('Hostel', 'Hostel')], max_length=130, null=True)),
                ('Notes', models.TextField(max_length=110)),
            ],
        ),
    ]
