# Generated by Django 2.1.7 on 2019-08-19 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190819_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpresence',
            old_name='Student_Attendance',
            new_name='Attendance',
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 9, 28, 25, 242187, tzinfo=utc)),
        ),
    ]
