# Generated by Django 2.1.7 on 2019-08-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_feetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('Student', models.CharField(max_length=130)),
                ('FeeAmount', models.CharField(max_length=130)),
                ('Month', models.CharField(max_length=130)),
                ('IsApplicableDiscount', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=130, null=True)),
                ('PaidStatus', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=130, null=True)),
                ('Notes', models.TextField(max_length=110)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation')),
                ('FeeType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.FeeType')),
            ],
        ),
    ]
