# Generated by Django 2.1.7 on 2019-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_feecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='FeeType',
            field=models.CharField(choices=[('General Fee', 'General Fee'), ('Transport', 'Transport'), ('Hostel', 'Hostel')], max_length=130, null=True),
        ),
    ]
