# Generated by Django 2.1.7 on 2019-08-19 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190819_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 10, 16, 51, 356913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Student_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.TeachersInformation'),
        ),
    ]
