# Generated by Django 2.1.7 on 2019-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190801_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('ExpenditureHead', models.CharField(choices=[('General', 'General'), ('Others', 'Others')], max_length=130, null=True)),
                ('ExpenditureMethod', models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash')], max_length=130, null=True)),
                ('Amount', models.CharField(max_length=130)),
                ('Date', models.CharField(max_length=130)),
                ('Notes', models.TextField(max_length=50)),
            ],
        ),
    ]
