# Generated by Django 2.1.7 on 2019-08-20 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190819_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='ClassName',
            field=models.CharField(choices=[('Form_One', 'Form_One'), ('Form_Two', 'Form_Two'), ('Form_Three', 'Form_Three'), ('Form_Four', 'Form_Four'), ('Form_Five_Arts', 'Form_Five_Arts'), ('Form_Five_Sciences', 'Form_Five_Sciences'), ('Form_Five_Six', 'Form_Six_Arts'), ('Form_Six_Sciences', 'Form_Six_Sciences')], max_length=130),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 6, 57, 6, 32631, tzinfo=utc)),
        ),
    ]
