# Generated by Django 2.1.7 on 2019-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_expenditure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('EventTitle', models.CharField(max_length=130)),
                ('EventFor', models.CharField(max_length=130)),
                ('EventPlace', models.CharField(max_length=130)),
                ('Amount', models.CharField(max_length=130)),
                ('FromDate', models.CharField(max_length=130)),
                ('ToDate', models.CharField(max_length=130)),
                ('Image', models.FileField(max_length=130, upload_to='')),
                ('Notes', models.TextField(max_length=50)),
            ],
        ),
    ]
