# Generated by Django 2.1.7 on 2019-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('NoticeTitle', models.CharField(max_length=130)),
                ('NoticeFor', models.CharField(max_length=130)),
                ('Notice', models.TextField(max_length=130)),
            ],
        ),
    ]
