# Generated by Django 2.1.7 on 2019-08-21 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190820_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assignment',
            field=models.FileField(default='text', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 11, 4, 54, 252848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], max_length=130),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='Syllabus',
            field=models.FileField(default='text', upload_to='gallery'),
        ),
    ]
