# Generated by Django 2.1.7 on 2019-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_notice_noticedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('NewsTitle', models.CharField(max_length=130)),
                ('Date', models.CharField(default='02-July-2019', max_length=130)),
                ('Image', models.FileField(max_length=130, upload_to='')),
                ('News', models.TextField(max_length=130)),
            ],
        ),
    ]
