# Generated by Django 2.1.7 on 2019-08-22 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190822_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='Student',
        ),
        migrations.AddField(
            model_name='feecollection',
            name='Student_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.DataStudent'),
        ),
        migrations.AlterField(
            model_name='datastudent',
            name='name',
            field=models.CharField(default='Student_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 22, 7, 13, 52, 6897, tzinfo=utc)),
        ),
    ]
