# Generated by Django 2.1.7 on 2019-08-27 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20190822_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guardian name', max_length=100)),
                ('phone', models.CharField(default='phone number', max_length=150)),
                ('profession', models.CharField(default='career', max_length=100)),
                ('Present_Address', models.CharField(default='current area', max_length=100)),
                ('Permanent_Address', models.CharField(default='home', max_length=100)),
                ('National_Id', models.CharField(default='Use NIN', max_length=150)),
                ('religion', models.CharField(choices=[('moslem', 'moslem'), ('Christian', 'Christian'), ('Others', 'Others')], max_length=130)),
                ('Role', models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Uncle', 'Uncle'), ('Auntie', 'Auntie'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='next of kin', max_length=130)),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=130)),
                ('Email', models.CharField(default='email', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('Other_Info', models.CharField(default='Notes', max_length=130)),
                ('Photo', models.ImageField(default='text', upload_to='gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 27, 5, 15, 9, 756787, tzinfo=utc)),
        ),
    ]
