# Generated by Django 2.1.7 on 2019-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=130)),
                ('HolidayTitle', models.CharField(max_length=130)),
                ('FromDate', models.CharField(max_length=130)),
                ('ToDate', models.CharField(max_length=130)),
                ('Notes', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
