# Generated by Django 2.1.7 on 2019-08-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=130)),
                ('AdmissionNo', models.CharField(max_length=130)),
                ('AdmissionDate', models.CharField(max_length=130)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=130)),
                ('DateOfBirth', models.CharField(max_length=130)),
                ('BloodType', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB-')], max_length=130)),
                ('Religion', models.CharField(max_length=130)),
                ('Guardian', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('U', 'Uncle'), ('A', 'Auntie'), ('MU', 'Maternal'), ('O', 'Others')], max_length=130)),
                ('RelationshipWithGuardian', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB-')], max_length=130)),
                ('PresentAdress', models.CharField(max_length=130)),
                ('PermanentAddress', models.CharField(max_length=130)),
                ('Phone', models.CharField(max_length=130)),
                ('NationalId', models.CharField(max_length=130)),
                ('Group', models.CharField(choices=[('A', 'Arts'), ('S', 'Sciences')], max_length=130)),
                ('RollNo', models.CharField(max_length=130)),
                ('RegistrationNo', models.CharField(max_length=130)),
                ('SecondLang', models.CharField(max_length=130)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Classinformation')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Subjects')),
            ],
        ),
    ]
