# Generated by Django 2.1.7 on 2019-08-30 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20190830_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 9, 22, 24, 358005, tzinfo=utc)),
        ),
    ]
