# Generated by Django 2.1.7 on 2019-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20190803_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Image',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='library',
            name='BookCover',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
