# Generated by Django 2.1.7 on 2019-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190805_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchooCode', models.CharField(max_length=130)),
                ('SchooName', models.CharField(max_length=130)),
                ('Address', models.CharField(max_length=130)),
                ('Phone', models.CharField(max_length=130)),
                ('DateOfRegistration', models.CharField(max_length=130)),
            ],
        ),
    ]
