# Generated by Django 2.1.7 on 2019-08-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='events',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='examsuggestion',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='hostelrooms',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='income',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='library',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='news',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='route',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='visitorinfor',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School'),
        ),
    ]
