# Generated by Django 2.1.7 on 2019-08-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20190805_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_username', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_religion', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=15)),
                ('student_address', models.CharField(max_length=100)),
                ('student_birth_date', models.CharField(max_length=100)),
                ('student_health_condition', models.CharField(max_length=100)),
                ('student_reg_no', models.CharField(max_length=100)),
                ('student_admission_no', models.CharField(max_length=100)),
                ('student_admission_date', models.CharField(max_length=100)),
                ('student_previous_class', models.CharField(max_length=100)),
                ('student_previous_school', models.CharField(max_length=100)),
                ('student_image', models.FileField(upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School')),
            ],
        ),
    ]
