# Generated by Django 2.1.7 on 2019-08-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20190805_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_favorite',
        ),
    ]
