# Generated by Django 2.1.7 on 2019-08-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_student_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_admission_date',
            field=models.DateField(max_length=100),
        ),
    ]
