# Generated by Django 2.1.7 on 2019-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20190806_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='FromDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='events',
            name='ToDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='ExamDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='StartDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='Date',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='FromDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='ToDate',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='income',
            name='Date',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.CharField(default='02-July-2019', max_length=130),
        ),
        migrations.AlterField(
            model_name='notice',
            name='NoticeDate',
            field=models.CharField(default='02-July-2019', max_length=130),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='school',
            name='DateOfRegistration',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_date',
            field=models.CharField(max_length=100),
        ),
    ]
