# Generated by Django 2.1.7 on 2019-08-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190806_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=130)),
                ('NationaId', models.CharField(max_length=130)),
                ('Responsibility', models.CharField(max_length=130)),
                ('Gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('Religion', models.CharField(max_length=130)),
                ('DateOfBirth', models.DateField(default='15-10-1990', max_length=130)),
                ('PermanentAddress', models.CharField(max_length=130)),
                ('PresentAddress', models.CharField(max_length=130)),
                ('Email', models.CharField(max_length=130)),
                ('Password', models.CharField(max_length=130)),
                ('Username', models.CharField(max_length=130)),
                ('SalaryType', models.CharField(choices=[('Monthly', 'Monthly'), ('hourly', 'hourly')], max_length=10)),
                ('JoiningDate', models.DateField(default='15-10-1990', max_length=130)),
                ('Resume', models.FileField(upload_to='gallery')),
                ('TeacherPhoto', models.FileField(upload_to='gallery')),
                ('OtherInfo', models.TextField(default='Enter Other Notes', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='School',
        ),
        migrations.AlterField(
            model_name='classinformation',
            name='ClassTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.TeachersInformation'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.TeachersInformation'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='SubjectTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.TeachersInformation'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='teachersinformation',
            name='Salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.SalaryGrade'),
        ),
    ]
