# Generated by Django 2.1.7 on 2019-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20190806_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinformation',
            name='DateOfBirth',
            field=models.CharField(default='15-10-1990', max_length=130),
        ),
    ]
