# Generated by Django 2.1.7 on 2019-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20190806_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='student_school',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teachersinformation',
            name='TeacherPhoto',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
