# Generated by Django 2.1.7 on 2019-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20190807_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinformation',
            name='religion',
            field=models.CharField(choices=[('moslem', 'moslem'), ('Christian', 'Christian'), ('Others', 'Others')], max_length=130),
        ),
    ]
