# Generated by Django 2.1.7 on 2019-08-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20190807_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsInformation',
            new_name='StudentInformation',
        ),
    ]
