# Generated by Django 2.1.7 on 2019-08-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20190807_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=130)),
                ('religion', models.CharField(choices=[('moslem', 'moslem'), ('Christian', 'Christian'), ('Others', 'Others')], max_length=130)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('health_condition', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('admission_no', models.CharField(max_length=100)),
                ('admission_date', models.DateField(max_length=100)),
                ('previous_class', models.CharField(max_length=100)),
                ('previous_school', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.School')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='school',
        ),
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
