# Generated by Django 2.1.7 on 2019-08-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20190807_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='admission_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='birth_date',
            field=models.DateField(max_length=100),
        ),
    ]
