# Generated by Django 2.1.7 on 2019-08-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190809_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='ClassName',
            field=models.CharField(choices=[('Form One', 'Form One'), ('Form Two', 'Form Two'), ('Form Three', 'Form Three'), ('Form Four', 'Form Four'), ('Form Five Arts', 'Form Five Arts'), ('Form Five Sciences', 'Form Five Sciences'), ('Form Five Six', 'Form Six Arts'), ('Form Six Sciences', 'Form Six Sciences')], max_length=130),
        ),
        migrations.AlterField(
            model_name='sectioninformation',
            name='SectionName',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=130),
        ),
    ]
