# Generated by Django 2.1.7 on 2019-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20190812_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='FatherDesignation',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='FatherName',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='FatherPhone',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='FatherPhoto',
            field=models.ImageField(default='text', upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='FatherProfession',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='MotherDesignation',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='MotherName',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='MotherPhone',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='MotherPhoto',
            field=models.ImageField(default='text', upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='MotherProfession',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='TransferCertificate',
            field=models.ImageField(default='text', upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
