# Generated by Django 2.1.7 on 2019-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20190813_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Guardian',
            field=models.CharField(default='text', max_length=130),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='GuardianRelationshipToStudent',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother', 'Mother'), ('Father', 'Father'), ('Uncle', 'Uncle'), ('Auntie', 'Auntie')], default='text', max_length=130),
        ),
    ]
