# Generated by Django 2.1.7 on 2019-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20190813_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='address',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='NationaId',
            field=models.CharField(default='Use NIN', max_length=150),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='PermanentAddress',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='PresentAddress',
            field=models.CharField(default='current area', max_length=100),
        ),
    ]
