# Generated by Django 2.2.4 on 2019-09-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190907_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Year'),
        ),
    ]
